### ISSUE TITLE
basis set input with block makes it crash

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#199]
version c4e553105

I have created a project with this input. It runs when I run it without GUI.
The reason was that I tried to set up a rather arbitrary basis set, and remain in guided mode.

```
geometry={
2

be 0 0 0 
s 0 2 0
}
basis
default=cc-pV(T+d)Z-PP
be=def2-svp
end

core,small
{rhf}
{mp2}

put,molden,canonical.molden



```
When I open this with imolpro, it crashes:

```
python iMolpro.py 
Traceback (most recent call last):
  File "/home/doll/imolpro/iMolpro/ProjectWindow.py", line 580, in run
    if self.guided_possible() and ('geometry' not in self.input_specification or (
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doll/imolpro/iMolpro/ProjectWindow.py", line 471, in guided_possible
    input_specification = InputSpecification(input_text, directory=self.project.filename())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doll/imolpro/iMolpro/molpro_input.py", line 79, in __init__
    self.parse(input)
  File "/home/doll/imolpro/iMolpro/molpro_input.py", line 185, in parse
    raise ValueError('** warning should not happen basis', line)
ValueError: ('** warning should not happen basis', 'basis')

```

**Comment by pjknowles** [comment]
That's right, `basis`...`end` is not parsed, and probably it should be, since it is documented. But first the code should be fixed so that it does not crash with this input, but simply conclude that guided mode is not possible.

**Comment by klauspdoll** [comment]
Thanks, works.
