### ISSUE TITLE
Automated build for intel macOS produces bad binary

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#224]
> Traceback (most recent call last):
>   File "iMolpro.py", line 9, in <module>
>     from settings import settings
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
>   File "settings.py", line 10, in <module>
>     os.environ['APPDATA' if platform.system() == 'Windows' else 'HOME']) / '.molpro' / 'iMolpro.settings.json'))
>     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen os>", line 685, in __getitem__
> KeyError: 'HOME'

**Comment by pjknowles** [comment]
Switching to running on GitHub-hosted runners, it's still the same problem at run time:
```
% /Volumes/dist\ 3/iMolpro.app/Contents/MacOS/iMolpro                         ✭
Traceback (most recent call last):
  File "iMolpro.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "settings.py", line 10, in <module>
  File "<frozen os>", line 714, in __getitem__
KeyError: 'HOME'
[PYI-75789:ERROR] Failed to execute script 'iMolpro' due to unhandled exception: 'HOME'
[PYI-75789:ERROR] Traceback:
Traceback (most recent call last):
  File "iMolpro.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "settings.py", line 10, in <module>
  File "<frozen os>", line 714, in __getitem__
KeyError: 'HOME'

Traceback (most recent call last):
  File "iMolpro.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "Chooser.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "RecentMenu.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "pymolpro/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "pymolpro/orbital.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "scipy/__init__.py", line 67, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "scipy/_lib/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "scipy/_lib/_testutils.py", line 21, in <module>
  File "packaging/tags.py", line 558, in sys_tags
  File "packaging/tags.py", line 224, in cpython_tags
  File "packaging/tags.py", line 415, in mac_platforms
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['/Volumes/dist 3/iMolpro.app/Contents/MacOS/iMolpro', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 1.
[PYI-75788:ERROR] Failed to execute script 'iMolpro' due to unhandled exception: Command '['/Volumes/dist 3/iMolpro.app/Contents/MacOS/iMolpro', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 1.
[PYI-75788:ERROR] Traceback:
Traceback (most recent call last):
  File "iMolpro.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "Chooser.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "RecentMenu.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "pymolpro/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "pymolpro/orbital.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "scipy/__init__.py", line 67, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "scipy/_lib/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "scipy/_lib/_testutils.py", line 21, in <module>
  File "packaging/tags.py", line 558, in sys_tags
  File "packaging/tags.py", line 224, in cpython_tags
  File "packaging/tags.py", line 415, in mac_platforms
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['/Volumes/dist 3/iMolpro.app/Contents/MacOS/iMolpro', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 1.
```
