### ISSUE TITLE
new project, run job, "Move to", now 2 project windows are open, close window with old project name, crash

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#259]
version 2e5fab0be6

1 ) create new project: bla10.molpro

2 ) load H2O geometry, run job

3 ) Projects/Move to ...   move project to bla11.molpro 

4 ) Now **two** windows are opened: bla10.molpro and bla11.molpro

5 ) use window with bla10.molpro , Projects/Close, crash like this:

```
Traceback (most recent call last):
  File "/home/doll/imolpro/iMolpro/WindowManager.py", line 29, in unregister
    self.openWindows.remove(widget)
ValueError: list.remove(x): x not in list
Aborted (core dumped)
```

**Comment by pjknowles** [comment]
I see only the correct behaviour - the bla11 window is open. However if I rename that again to bla12, it does crash:

```
Traceback (most recent call last):
  File "/Users/peterk/trees/iMolpro/ProjectWindow.py", line 81, in refresh_output_file
    latest_filename = self.project.filename(self.suffix, run=self.instance)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/iMolpro/lib/python3.12/site-packages/pysjef/project.py", line 454, in filename
    return self._project_wrapper.filename(suffix, name, run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pysjef/project_wrapper.pyx", line 123, in pysjef.project_wrapper.ProjectWrapper.filename
RuntimeError: filesystem error: in last_write_time: No such file or directory ["/private/tmp/bla11.molpro/Info.plist"]
```

**Comment by pjknowles** [comment]
Please reopen if the problem still exists.
